ARDUINO_DIR  = ../../../../arduino/arduino-1.8.1
ARDMK_DIR    = ./Arduino-Makefile
BOARD_TAG    = uno
USER_LIB_PATH = ../../arduino/
ARDUINO_LIBS = WireBus EEPROM 
include Arduino-Makefile/Arduino.mk

